# Generated by Django 6.1.1 on 2026-09-14 19:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Salon',
        ),
    ]
