# Generated by Django 6.1.1 on 2026-09-17 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salons', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='salon',
            name='closing_time',
            field=models.TimeField(default='21:00'),
        ),
        migrations.AddField(
            model_name='salon',
            name='opening_time',
            field=models.TimeField(default='09:00'),
        ),
    ]
